spring:
  application:
    name: pleasedeposit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
        ddl-auto: none
    generate-ddl: false
    show-sql: true
  output:
    ansi:
      enabled: always

oauth:
  login-redirect-uri: http://localhost:5173/main
  kakao:
    redirect-uri: http://localhost:8080/login/kakao/callback

---
spring:
  config:
    activate:
      on-profile: prod

oauth:
  login-redirect-uri: /main
  kakao:
    redirect-uri: https://pleasedeposit.tk/login/kakao/callback